apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nginx-demo-environment
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: nginx-demo-environment
    creationPolicy: Owner
  data:
    - secretKey: demo-secret
      remoteRef:
        key: {{ .Values.awsSecretName | quote }}
        property: demo-secret
