apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.hostname | quote }}
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.hostname | quote }}
      secretName: nginx-demo-tls
  rules:
    - host: {{ .Values.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  name: http
